# use {name} to player name
# use {item} to item name

item-msg: "Name: {item} "

#use {name} to player name
#use {x} to get player X
#use {y} to get player Y
#use {z} to get player Z

coor-msg: "X: {x} Y: {y} Z: {z}"

#this is [i] message can be repace to item-msg
#orginal is [i]

item-msg: "[i]"


#this is [coor] message can be replace to coor-msg
#original is [coor]

coor-msg: "[coor]
